site_name: Leila's

theme: 
  name: journal

nav:
  - Home: index.md
  - Sprints: sprints.md
  - Base:
    - Extras: 
        - Identidade Visual: base/identidade-visual.md
        - Protótipo de Baixa Fidelidade: base/prototipo-baixa.md
    - Módulo Projeto Não Orientado a Abordagens Específicas:
      - Design Sprint: base/design-sprint.md
      - Prototipação:
        - Protótipo de Alta Fidelidade: base/prototipo-alta.md
        - Testes de protótipos: base/teste-prototipo.md
      - Requisitos: 
        - Pré rastreabilidade: 
          - Rich Picture: base/rich-picture.md
          - 5W2H: base/5w2h.md
          - Mapa Mental: base/mapa-mental.md
          - Diagrama de causa e efeito: base/causa-efeito.md
          - Plano de gerenciamento de riscos: base/plano-de-risco.md
          - Estimativas: base/estimativas.md  
        - Elicitação:
          - Brainstorming: base/brainstorming.md
          - Questionário: base/questionario.md
          - Entrevista: base/entrevista.md
          - MoSCoW: base/moscow.md
          - Reuniões: base/reunioes.md
    - Módulo Processos/Metodologias/Abordagens:
      - Metodologia: base/metodologia.md
      - Modelagem BPMN: base/bpmn.md
  - Modelagem:
    - Módulo Projeto Orientado a Abordagens Tradicionais:
      - Modelagem Ágil: base/backlog.md 
      - Notação UML – Diagramas Estáticos: 
        - Diagrama de Classes: modelagem/classes.md
        - Diagrama de Agregação e Composição: modelagem/agregacao-composicao.md
        - Diagrama de Componentes: modelagem/diagrama-componentes.md
        - Diagrama de Pacotes: modelagem/pacotes.md
        - Diagrama de Classe Abstrata: modelagem/diagrama-abstrata.md
      - Notação UML – Diagramas Dinâmicos:
        - Diagrama de Sequência: modelagem/diagrama-sequencia.md
        - Diagrama de Comunicação: modelagem/diagrama_comunicacao.md
        - Diagrama de Atividades: modelagem/diagrama_atividades.md
        - Diagrama de Estados: modelagem/diagrama-estados.md
    - Extras:
      - Diagrama de Casos de Uso: modelagem/diagrama-casos-uso.md
      - Diagrama Relacional: modelagem/diagrama-relacional.md
  - Padrões de Projeto:
    - Módulo Padrões de Projeto GRASPs: padroes/grasps.md
    - Módulo Padrões de Projeto GoFs: padroes/gofs.md
      # - GOF Abstract: padroes/gof-abstract-factory.md
      # - GOF Singleton: padroes/gof-singleton.md
  #   - Módulo Padrões de Projeto Extras:
  #     - x: base/
  # - Arquitetura de Software & Reutilização:
  #   - Módulo Estilos e Padrões Arquiteturais:
  #     - x: base/
  #   - Módulo Reutilização de Software: 
  #     - x: base/
