site_name: Leila's

theme: journal
# theme: cosmo
# theme: flatly
# theme: litera
# theme: lumen
# theme: minty
# theme: pulse
# theme: simplex
# theme: united
# theme: gitbook

nav:
  - Home: index.md
  - Base:
    - Módulo Projeto Não Orientado a Abordagens Específicas:
      - Design Sprint: base/design-sprint.md
      - Requisitos: 
        - Pré rastreabilidade: 
          - Rich Picture: base/rich-picture.md
          - 5W2H: base/5w2h.md
          - Mapa Mental: base/mapa-mental.md
          - Diagrama de causa e efeito: base/causa-efeito.md
        - Elicitação:
          - Brainstorming: base/brainstorming.md
        - Modelagem: base/
    - Módulo Processos/Metodologias/Abordagens:
      - x: base/
  - Modelagem:
    - Módulo Projeto Orientado a Abordagens Tradicionais:
      - Notação UML – Diagramas Estáticos: base/
      - Notação UML – Diagramas Dinâmicos: base/
      - Modelagem Ágil: base/
  - Padrões de Projeto:
    - Módulo Padrões de Projeto GRASPs:
      - x: base/
    - Módulo Padrões de Projeto GoFs:
      - x: base/
    - Módulo Padrões de Projeto Extras:
      - x: base/
  - Arquitetura de Software & Reutilização:
    - Módulo Estilos e Padrões Arquiteturais:
      - x: base/
    - Módulo Reutilização de Software: 
      - x: base/