site_name: Leila's

theme: 
  name: journal
  include_sidebar: true

nav:
  - Home: index.md
  - Base:
    - Módulo Projeto Não Orientado a Abordagens Específicas:
      - Design Sprint: base/design-sprint.md
      - Prototipação:
        - Protótipo de Baixa Fidelidade: base/prototipo-baixa.md
        - Protótipo de Alta Fidelidade: base/prototipo-alta.md
        - Testes de protótipos: base/teste-prototipo.md
      - Identidade Visual: base/identidade-visual.md
      - Requisitos: 
        - Pré rastreabilidade: 
          - Rich Picture: base/rich-picture.md
          - 5W2H: base/5w2h.md
          - Mapa Mental: base/mapa-mental.md
          - Diagrama de causa e efeito: base/causa-efeito.md
          - Plano de gerenciamento de riscos: base/plano-de-risco.md
          - Estimativas: base/estimativas.md  
        - Elicitação:
          - Brainstorming: base/brainstorming.md
          - Questionário: base/questionario.md
          - Entrevista: base/entrevista.md
          - MoSCoW: base/moscow.md
          - Backlog: base/backlog.md 
          - Reuniões: base/reunioes.md
    - Módulo Processos/Metodologias/Abordagens:
      - Metodologia: base/metodologia.md
      - Modelagem BPMN: base/bpmn.md
  - Modelagem:
    - Módulo Projeto Orientado a Abordagens Tradicionais:
      - Notação UML – Diagramas Estáticos:
        - Diagrama de Agregação e Composição: modelagem/agregacao-composicao.md
      - Notação UML – Diagramas Dinâmicos:
      #  - Modelagem Ágil:
        - Diagramas de Atividades: modelagem/diagrama_atividades.md
  # - Padrões de Projeto:
  #   - Módulo Padrões de Projeto GRASPs:
  #     - x: base/
  #   - Módulo Padrões de Projeto GoFs:
  #     - x: base/
  #   - Módulo Padrões de Projeto Extras:
  #     - x: base/
  # - Arquitetura de Software & Reutilização:
  #   - Módulo Estilos e Padrões Arquiteturais:
  #     - x: base/
  #   - Módulo Reutilização de Software: 
  #     - x: base/